{{ $scope := . }}
{{- range $k, $v := .Values.nodes -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quorum-node{{ $k | substr 4 6}}-pvc
  annotations:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $scope.Values.quorum.storageSize }}
---
{{ end }}
