
{{- range $k, $v := .Values.nodes -}}
---

# nodekey private to the node, used to verify identity.
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node{{ $k | substr 4 6 }}-nodekey-config
  
  labels:
    app: quorum
    name: quorum-node{{ $k | substr 4 6 }}-nodekey-config
data:
  nodekey: |
    {{ $v.nodekey }}
    

# Only IBFT / istanbul networks need access to the nodekey address.

---
# enode Id
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node{{ $k | substr 4 6 }}-enode-config
  
  labels:
    app: quorum
    name: quorum-node{{ $k | substr 4 6 }}-enode-config
data:
  enode: |
    {{ $v.enode }}
---
# ethereum / geth account keys (keystore)
# @Keystore_File=Dir[@Key_Dir_Base + "/" + @Node_Key_Dir + "/UTC*"][0]
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node{{ $k | substr 4 6 }}-account-key-config
  
  labels:
    app: quorum
    name: quorum-node{{ $k | substr 4 6 }}-account-key-config
data:
  key: |-
    {{ $v.key }}

# end node

---
{{- end -}}