{{ $scope := . }}
{{- if eq $scope.Values.epirus.enabled true }}
  {{- if eq $scope.Values.epirus.ingress true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epirus-web-ingress
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: epirus-chain-explorer-web
            port:
              number: {{ $scope.Values.epirus.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: epirus-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: epirus-chain-explorer-api
            port:
              number: 8090
  {{- end }}
{{- end }}
---